---
- Web:
    - calendar:
        - href: "https://calendar.google.com/calendar/"
          icon: google-calendar
    - Gemini:
        - href: "https://gemini.google.com/"
          icon: google-gemini
    - drive:
        - href: "https://drive.google.com/"
          icon: google-drive
    - gmail:
        - href: "https://mail.google.com/mail/u/0/#inbox"
          icon: gmail
    - maps:
        - href: "https://google.com/maps"
          icon: google-maps
    - openslum:
        - href: "https://open-slum.org/"
          icon: google-play-books
    - annas-archive:
        - href: "https://annas-archive.org/"
          icon: google-play-books
    - Github:
        - abbr: GH
          href: https://github.com/
          icon: github
    - blog:
        - abbr: ip
          href: "http://blog.ianpreston.ca/"
    - Databricks Academy:
        - abbr: db
          icon: "https://www.svgrepo.com/show/330261/databricks.svg"
          href: "https://customer-academy.databricks.com/learn/signin"
