---
- Infrastructure:
    - pfsense:
        href: "https://behemoth.ipreston.net:10443"
        icon: pfsense
        description: router
    - laconia:
        href: "http://laconia.ipreston.net"
        icon: synology
        description: NAS
        widget:
          type: diskstation
          url: "https://laconia.ipreston.net"
          username: "ipreston"
          password: "{{HOMEPAGE_VAR_LACONIA_PASSWORD}}"
          fields: ["volumeAvailable", "resources.cpu", "resources.mem"]
    - unifi:
        href: "https://192.168.10.41:8443"
        icon: unifi
        description: WiFi controller
    - blikvm:
        href: "http://blikvm.ipreston.net"
        icon: "pikvm"
        description: "KVM over IP"
