---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app actualbudget
  namespace: flux-system
spec:
  dependsOn:
    - name: envoy-gateway-config
    - name: longhorn-config
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./k8s/apps/actualbudget/${clusterpath}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: actualbudget
  timeout: 5m
  wait: true
  images:
    - name: actualbudget/actual-server
      # renovate: datasource=docker depName=actualbudget/actual-server
      newTag: "26.1.0"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
