# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kuard
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-config
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./k8s/apps/kuard/${clusterpath}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kuard
  timeout: 5m
  wait: true
  images:
    - name: nginx
      # renovate: datasource=docker depName=nginx
      newTag: "1.29.3"
