---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app miniflux
  namespace: flux-system
spec:
  components:
    - ../../components/postgres
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      # Check if the 'Ready' condition is 'True'
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      # Optional: Explicitly fail if 'Ready' is 'False' (usually Flux just waits)
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
  dependsOn:
    - name: envoy-gateway-config
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./k8s/apps/miniflux/${clusterpath}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *app
  timeout: 5m
  wait: true
  images:
    - name: ghcr.io/miniflux/miniflux
      # renovate: datasource=docker depName=ghcr.io/miniflux/miniflux
      newTag: "2.2.15-distroless"
  postBuild:
    substitute:
      APP: *app
      DB_STORAGE: 2Gi
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
