---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clusterrole.yaml
  - deployment.yaml
  - http-route.yaml
  - secret.yaml
  - service-account.yaml
  - service.yaml
# Generate the ConfigMap
configMapGenerator:
  - name: homepage
    files:
      - configs/kubernetes.yaml
      - configs/custom.css
      - configs/custom.js
      - configs/settings.yaml
      - configs/bookmarks.yaml
      - configs/services.yaml
      - configs/widgets.yaml
      - configs/docker.yaml
