---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../../components/namespace
resources:
  - ./external-secret.yaml
  - ./alertmanagerconfig.yaml
  - ./helmrelease.yaml
  - ./securitypolicy.yaml
patches:
  - target:
      kind: Namespace
      name: monitoring
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
        labels:
          pod-security.kubernetes.io/enforce: privileged
