---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-route
  namespace: longhorn
  annotations:
    gethomepage.dev/enabled: true
    gethomepage.dev/description: Cluster Storage
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Longhorn
    gethomepage.dev/icon: longhorn
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=longhorn-ui"
spec:
  parentRefs:
    - name: envoy-internal
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - "longhorn.${subdomain}.ipreston.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: longhorn-frontend
          port: 80
