---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: longhorn-auth-policy
  namespace: longhorn-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: longhorn-route
  extAuth:
    headersToExtAuth:
      - cookie
    http:
      backendRefs:
        - name: ak-outpost-proxy-outpost
          namespace: authentik
          port: 9000
      # Authentik Envoy implementation requires this specific path
      path: /outpost.goauthentik.io/auth/envoy
      # # Pass these headers to Authentik so it knows which app is being accessed
      headersToBackend:
        - set-cookie
        - x-authentik-*
