---
kind: Namespace
apiVersion: v1
metadata:
  name: actualbudget
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: actualbudget-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: actualbudget
  namespace: actualbudget
  labels:
    app.kubernetes.io/instance: actualbudget
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/service: actualbudget
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5006
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: actualbudget
    app.kubernetes.io/name: actualbudget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
  namespace: actualbudget
  labels:
    app.kubernetes.io/instance: actualbudget
    app.kubernetes.io/name: actualbudget
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: actualbudget
      app.kubernetes.io/instance: actualbudget
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: actualbudget
        app.kubernetes.io/name: actualbudget
    spec:
      containers:
        - name: main
          image: actualbudget/actual-server:not-used
          volumeMounts:
            - name: actualbudget-pv
              mountPath: /data
      volumes:
        - name: actualbudget-pv
          persistentVolumeClaim:
            claimName: actualbudget-pvc
