---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: actualbudget-route
  namespace: actualbudget
  annotations:
    gethomepage.dev/enabled: true
    gethomepage.dev/description: Budget Tracker
    gethomepage.dev/group: Consumption
    gethomepage.dev/name: Actualbudget
    gethomepage.dev/icon: actual-budget
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=actualbudget"
spec:
  parentRefs:
    - name: envoy-internal
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - "actualbudget.${subdomain}.ipreston.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: actualbudget
          port: 80
