---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-cnpg-db
  namespace: ${APP}
spec:
  description: Postgres cluster for ${APP}
  imageCatalogRef:
    kind: ClusterImageCatalog
    apiGroup: postgresql.cnpg.io
    name: standard-postgres-catalog
    major: ${PG_MAJOR}
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  monitoring:
    enablePodMonitor: true
  instances: 2
  storage:
    size: ${DB_STORAGE:=5Gi}
    storageClass: longhorn-cnpg-strict-local
  bootstrap:
    initdb:
      database: ${APP}
      owner: ${APP}
