---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ${APP}-cnpg-monitor
  namespace: ${APP}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: ${APP}-cnpg-db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
          targetLabel: cluster
        - sourceLabels: [__meta_kubernetes_pod_label_cnpg_io_instance]
          targetLabel: instance
        - sourceLabels: [__meta_kubernetes_pod_label_cnpg_io_node_role]
          targetLabel: role
