---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: standard-postgres-catalog
spec:
  images:
    - major: 17
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql versioning=semver:^17
      image: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie
    - major: 18
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql versioning=semver:^18
      image: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie
