---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
spec:
  serviceSelector:
    matchLabels:
      lb-pool: ip-pool
  blocks:
    - start: "set_in_patch"
      stop: "set_in_patch"
