---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
components:
  - ../../../components/namespace
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./grafanadashboard.yaml
patches:
  - target:
      kind: Namespace
      name: longhorn
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: longhorn
        labels:
          pod-security.kubernetes.io/enforce: privileged
