---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spegel
components:
  - ../../../components/namespace
resources:
  - ./helmrelease.yaml
patches:
  - target:
      kind: Namespace
      name: spegel
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: spegel
        labels:
          pod-security.kubernetes.io/enforce: privileged
