---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: "GRAFANA_USER"
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: "GRAFANA_PASS"
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: "GRAFANA_CLIENT_ID"
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: "GRAFANA_CLIENT_SECRET"
