---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db-cnpg-v1
  namespace: miniflux
spec:
  description: Postgres cluster for the miniflux application
  imageCatalogRef:
    kind: ClusterImageCatalog
    apiGroup: postgresql.cnpg.io
    name: standard-postgres-catalog
    major: 17
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  monitoring:
    enablePodMonitor: true
  instances: 2
  storage:
    size: 2Gi
    storageClass: longhorn-cnpg-strict-local
  superuserSecret:
    name: miniflux-pg-superuser-secret
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
      secret:
        name: miniflux-pg-secret
