---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db-cnpg-v1
  namespace: miniflux
spec:
  description: Postgres cluster for the miniflux application
  imageName: ghcr.io/cloudnative-pg/postgresql:not-used
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  monitoring:
    enablePodMonitor: true
  instances: 2
  storage:
    size: 2Gi
    storageClass: local-path
  superuserSecret:
    name: miniflux-pg-superuser-secret
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
      secret:
        name: miniflux-pg-secret
