---
apiVersion: v1
kind: Service
metadata:
  name: &app miniflux
  namespace: *app
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
    app.kubernetes.io/service: *app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app miniflux
  namespace: *app
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: *app
        app.kubernetes.io/name: *app
    spec:
      containers:
        - env:
            - name: *app
              value: https://miniflux.${subdomain}.ipreston.net
            - name: LOG_DATE_TIME
              value: "1"
            - name: PORT
              value: "80"
            - name: RUN_MIGRATIONS
              value: "1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${APP}-cnpg-db-app
                  key: uri
          image: ghcr.io/miniflux/miniflux:not-used
          name: main
