---
apiVersion: v1
kind: Service
metadata:
  name: &app miniflux
  namespace: *app
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
    app.kubernetes.io/service: *app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app miniflux
  namespace: *app
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: *app
        app.kubernetes.io/name: *app
    spec:
      containers:
        - env:
            - name: *app
              value: https://miniflux.${subdomain}.ipreston.net
            - name: LOG_DATE_TIME
              value: "1"
            - name: PORT
              value: "80"
            - name: RUN_MIGRATIONS
              value: "1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${APP}-pg-secret
                  key: uri
          # - name: HELPER_POSTGRES_HOST
          #   value: ${APP}-cnpg-db-rw
          # - name: HELPER_POSTGRES_USER
          #   value: ${APP}
          #   valueFrom:
          #     secretKeyRef:
          #       name: ${APP}-pg-secret
          #       key: username
          # - name: HELPER_POSTGRES_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: ${APP}-pg-secret
          #       key: password
          # - name: DATABASE_URL
          #   value: "host=$(HELPER_POSTGRES_HOST) user=${APP} password=$(HELPER_POSTGRES_PASSWORD) dbname=${APP}"

          image: ghcr.io/miniflux/miniflux:not-used
          name: main
