---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-postgres-pass
  namespace: miniflux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: miniflux-pg-secret
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "miniflux"
        password: "{{ .POSTGRES_MINIFLUX_PASS }}"
  data:
    - secretKey: POSTGRES_MINIFLUX_PASS
      remoteRef:
        key: "POSTGRES_MINIFLUX_PASS"
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-encoded-postgres-pass
  namespace: miniflux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_ENCODED_MINIFLUX_PASS
      remoteRef:
        key: "POSTGRES_ENCODED_MINIFLUX_PASS"
