---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux
components:
  - ../../../components/namespace
resources:
  - ./external-secret.yaml
  - ./deployment.yaml
  - ./http-route.yaml
